pretrained_base_model_path: "./pretrained_weights/stable-diffusion-v1-5/"
pretrained_vae_path: "./pretrained_weights/sd-vae-ft-mse"
image_encoder_path: "./pretrained_weights/image_encoder"
denoising_unet_path: "/cephfs/SZ-AI/usr/liuchenyu/HaiLook/Moore-AnimateAnyone/pretrained_weights/opensource_stage1/denoising_unet-0.pth"
reference_unet_path: "/cephfs/SZ-AI/usr/liuchenyu/HaiLook/Moore-AnimateAnyone/pretrained_weights/opensource_stage1/reference_unet-0.pth"
pose_guider_path: "/cephfs/SZ-AI/usr/liuchenyu/HaiLook/Moore-AnimateAnyone/pretrained_weights/opensource_stage1/pose_guider-0.pth"
motion_module_path: "/cephfs/SZ-AI/usr/liuchenyu/HaiLook/Moore-AnimateAnyone/pretrained_weights/mm_sd_v15_v2.ckpt"
 #"/cephfs/SZ-AI/usr/liuchenyu/HaiLook/Moore-AnimateAnyone/stage2_out/mmV2_UbcSwitchBackground_fix/motion_module-1965.pth"
 #'/cephfs/SZ-AI/usr/liuchenyu/HaiLook/Moore-AnimateAnyone/pretrained_weights/motion_module.pth'
 # '/cephfs/SZ-AI/usr/liuchenyu/HaiLook/Moore-AnimateAnyone/pretrained_weights/mm_sd_v15_v2.ckpt'

inference_config: "./configs/inference/inference_v2.yaml"
weight_dtype: 'fp16'

test_cases:
  "./configs/inference/ref_images/anyone-2.png":
    - "./configs/inference/pose_videos/anyone-video-2_kps.mp4" 
    - "./configs/inference/pose_videos/anyone-video-5_kps.mp4"
  "./configs/inference/ref_images/anyone-10.png":
    - "./configs/inference/pose_videos/anyone-video-1_kps.mp4"
    - "./configs/inference/pose_videos/anyone-video-2_kps.mp4"
  "./configs/inference/ref_images/anyone-11.png":
    - "./configs/inference/pose_videos/anyone-video-1_kps.mp4"
    - "./configs/inference/pose_videos/anyone-video-2_kps.mp4"
  "./configs/inference/ref_images/anyone-3.png":
    - "./configs/inference/pose_videos/anyone-video-2_kps.mp4"
    - "./configs/inference/pose_videos/anyone-video-5_kps.mp4"
  "./configs/inference/ref_images/anyone-5.png":
    - "./configs/inference/pose_videos/anyone-video-2_kps.mp4" 
