data:
  train_bs: 2
  train_width: 512
  train_height: 512 
  meta_paths:
    - "/cephfs/SZ-AI/usr/liuchenyu/HaiLook/Moore-AnimateAnyone/data/withface_meta.json"
  sample_rate: 2 
  n_sample_frames: 16
  background_dir: "/cephfs/SZ-AI/usr/liuchenyu/HaiLook/Moore-AnimateAnyone/backgrounds"

solver:
  gradient_accumulation_steps: 1
  mixed_precision: 'fp16'
  enable_xformers_memory_efficient_attention: True 
  gradient_checkpointing: True 
  max_train_steps: 3000
  max_grad_norm: 1.0
  # lr
  learning_rate: 5e-5
  scale_lr: False 
  lr_warmup_steps: 1
  lr_scheduler: 'constant'

  # optimizer
  use_8bit_adam: True 
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay:  1.0e-2
  adam_epsilon: 1.0e-8

val:
  validation_steps: 50


noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "linear"
  steps_offset:        1
  clip_sample:         false

base_model_path: './pretrained_weights/stable-diffusion-v1-5'
vae_model_path: './pretrained_weights/sd-vae-ft-mse'
image_encoder_path: './pretrained_weights/sd-image-variations-diffusers/image_encoder'
mm_path: '/cephfs/SZ-AI/usr/liuchenyu/HaiLook/Moore-AnimateAnyone/pretrained_weights/v3_sd15_mm.ckpt'

weight_dtype: 'fp16'  # [fp16, fp32]
uncond_ratio: 0.1
noise_offset: 0.05
snr_gamma: 5.0
enable_zero_snr: True 
stage1_ckpt_dir: '/cephfs/SZ-AI/usr/liuchenyu/HaiLook/Moore-AnimateAnyone/pretrained_weights/opensource_stage1'
stage1_ckpt_step: 0

seed: 42
resume_from_checkpoint: '/cephfs/SZ-AI/usr/liuchenyu/HaiLook/Moore-AnimateAnyone/stage2_out/mmV3_lora_full_data_5e-5'
checkpointing_steps: 1764
exp_name: 'mmV3_lora_full_data_5e-5'
output_dir: './stage2_out' 